- name: Create groups
  group:
    name: "admin"
    state: present

- name: Create users
  user:
    name: "{{ item.login }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    groups: "{{ item.groups | join(',') }}"
    append: yes
  loop: "{{ users }}"

- name: Suoders
  copy:
    src: sudoers
    dest: /etc/sudoers.d/kippou
    owner: root
    group: root
    mode: '0440'
