- name: Create groups
  group:
    name: "admin"
    state: present

- name: Create users
  user:
    name: "{{ item.login }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups | join(',') }}"
    append: yes
  loop: "{{ users }}"
